server:
  port: 8089
spring:
  application:
    name: api-gateway

# zuul
zuul:
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  routes:
    #doker
    user:
      path: /users/**
      #url: http://user-service:8085/
      url: http://localhost:8085/
    notification:
      path: /notifications/**
      #url: http://notification-service:8086/
      url: http://localhost:8086/
    clientcare:
      path: /clientcares/**
      #url: http://clientcare-service:8087/
      url: http://localhost:8087/
    vehicle:
      path: /vehicles/**
      #url: http://vehicle-service:8088/
      url: http://localhost:8088/

# eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka