server:
  port: 8089
spring:
  application:
    name: api-gateway

# zuul
zuul:
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  routes:
    #user servis
    user:
      path: /users/**
      url: http://localhost:8085/
    notification:
      path: /notifications/**
      url: http://localhost:8086/

# eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka