// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvent.proto

package ba.unsa.etf.grpc;

/**
 * Protobuf enum {@code ActionType}
 */
public enum ActionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREATE = 0;</code>
   */
  CREATE(0),
  /**
   * <code>UPDATE = 1;</code>
   */
  UPDATE(1),
  /**
   * <code>DELETE = 2;</code>
   */
  DELETE(2),
  /**
   * <code>GET = 3;</code>
   */
  GET(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATE = 0;</code>
   */
  public static final int CREATE_VALUE = 0;
  /**
   * <code>UPDATE = 1;</code>
   */
  public static final int UPDATE_VALUE = 1;
  /**
   * <code>DELETE = 2;</code>
   */
  public static final int DELETE_VALUE = 2;
  /**
   * <code>GET = 3;</code>
   */
  public static final int GET_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ActionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ActionType forNumber(int value) {
    switch (value) {
      case 0: return CREATE;
      case 1: return UPDATE;
      case 2: return DELETE;
      case 3: return GET;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ActionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
          public ActionType findValueByNumber(int number) {
            return ActionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ba.unsa.etf.grpc.SystemEvent.getDescriptor().getEnumTypes().get(0);
  }

  private static final ActionType[] VALUES = values();

  public static ActionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ActionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ActionType)
}

