// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvent.proto

package ba.unsa.etf.grpc;

public interface SystemEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SystemEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseContent = 1;</code>
   * @return The responseContent.
   */
  java.lang.String getResponseContent();
  /**
   * <code>string responseContent = 1;</code>
   * @return The bytes for responseContent.
   */
  com.google.protobuf.ByteString
      getResponseContentBytes();

  /**
   * <code>.ResponseType responseType = 2;</code>
   * @return The enum numeric value on the wire for responseType.
   */
  int getResponseTypeValue();
  /**
   * <code>.ResponseType responseType = 2;</code>
   * @return The responseType.
   */
  ba.unsa.etf.grpc.ResponseType getResponseType();
}
