// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvent.proto

package ba.unsa.etf.grpc;

public final class SystemEvent {
  private SystemEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemEventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SystemEvent.proto\"\227\001\n\023SystemEventsRequ" +
      "est\022\021\n\ttimeStamp\030\001 \001(\t\022\024\n\014microservice\030\002" +
      " \001(\t\022\016\n\006action\030\003 \001(\t\022\020\n\010resource\030\004 \001(\t\022\020" +
      "\n\010response\030\005 \001(\t\022\017\n\007message\030\006 \001(\t\022\022\n\nidK" +
      "orisnik\030\007 \001(\003\"S\n\023SystemEventResponse\022\027\n\017" +
      "responseContent\030\001 \001(\t\022#\n\014responseType\030\002 " +
      "\001(\0162\r.ResponseType*9\n\nActionType\022\n\n\006CREA" +
      "TE\020\000\022\n\n\006UPDATE\020\001\022\n\n\006DELETE\020\002\022\007\n\003GET\020\003*&\n" +
      "\014ResponseType\022\013\n\007SUCCESS\020\000\022\t\n\005ERROR\020\0012A\n" +
      "\006action\0227\n\tlogAction\022\024.SystemEventsReque" +
      "st\032\024.SystemEventResponseB\024\n\020ba.unsa.etf." +
      "grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SystemEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SystemEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemEventsRequest_descriptor,
        new java.lang.String[] { "TimeStamp", "Microservice", "Action", "Resource", "Response", "Message", "IdKorisnik", });
    internal_static_SystemEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SystemEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemEventResponse_descriptor,
        new java.lang.String[] { "ResponseContent", "ResponseType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
